In [2]:
import numpy as np

In [60]:
# data = [[1, 2, 3, 4, 5,7,8,9,10], [6, 7, 8, 9, 10,11,12,13,14], [1,5,3,2,1,3,4,-1,0]]
data = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [1,5,3,2,1]]

data = np.array(data)
dataint = np.cos(data[0,:])
arr = np.concatenate((data, [dataint]), axis=0)
X = arr[:, :-1]
y = arr[:, 1:]
p = np.linalg.pinv(X)
A = y.dot(p)

In [44]:
print(arr.shape)
print(X.shape)
print(y.shape)
print(p.shape)
print(A.shape)

(4, 9)
(4, 8)
(4, 8)
(8, 4)
(4, 4)


In [63]:
print(X)

[[ 1.          2.          3.          4.        ]
 [ 6.          7.          8.          9.        ]
 [ 1.          5.          3.          2.        ]
 [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]]


In [61]:
print(p)

[[-0.46863315  0.25532167 -0.15575466  0.17112239]
 [ 0.32546739 -0.17871334  0.37698135  0.68448955]
 [-1.04503533  0.39146168 -0.28669871 -1.88234627]
 [ 0.98820109 -0.26807001  0.06547202  1.02673433]]


In [62]:
np.linalg.inv(X)

array([[-0.46863315,  0.25532167, -0.15575466,  0.17112239],
       [ 0.32546739, -0.17871334,  0.37698135,  0.68448955],
       [-1.04503533,  0.39146168, -0.28669871, -1.88234627],
       [ 0.98820109, -0.26807001,  0.06547202,  1.02673433]])

In [57]:
data = np.array([[2,1],[1,2]])
print(data)
p = np.linalg.pinv(data)
print(p)

[[2 1]
 [1 2]]
[[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]


In [48]:
data.dot(p)

array([[ 1.00000000e+00, -1.11022302e-16],
       [ 1.66533454e-16,  1.00000000e+00]])

In [59]:
np.linalg.inv(data)

array([[ 0.66666667, -0.33333333],
       [-0.33333333,  0.66666667]])

In [56]:
1.5/3

0.5